export const ACCOUNT_LOAD_ADDRESS = 'ACCOUNT_LOAD_ADDRESS';
export const ACCOUNT_LOAD_ADDRESS_SUCCESS = ' ACCOUNT_LOAD_ADDRESS_SUCCESS';

export const ORDER_CREATION = 'ORDER_CREATION';
export const ORDER_CREATION_SUCCESS = 'ORDER_CREATION_SUCCESS';

export const ORDERS_LOAD = 'ORDERS_LOAD';
export const ORDERS_LOAD_SUCCESS = 'ORDERS_LOAD_SUCCESS';

export const ORDER_ACTION = 'ORDER_ACTION';
export const ORDER_ACTION_SUCCESS = 'ORDER_ACTION_SUCCESS';